# Generated by Django 3.1.7 on 2021-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_group_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
