# Generated by Django 3.1.7 on 2021-03-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_image'),
        ('posts', '0005_auto_20210320_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
