# Generated by Django 3.1.7 on 2021-03-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_image'),
        ('posts', '0006_post_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_of_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
