# Generated by Django 3.1.7 on 2021-03-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_group_of_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='image_five',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_four',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_one',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_seven',
            new_name='image_4',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_six',
            new_name='image_5',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_three',
            new_name='image_6',
        ),
        migrations.RenameField(
            model_name='postimages',
            old_name='image_two',
            new_name='image_7',
        ),
    ]
