# Generated by Django 3.1.7 on 2021-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_one',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_three',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_two',
            field=models.ImageField(null=True, upload_to='events'),
        ),
    ]
