# Generated by Django 3.1.7 on 2021-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('website', models.CharField(max_length=500)),
                ('email', models.TextField()),
                ('instagram', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('privacy', models.BooleanField(default=False)),
                ('display_social', models.BooleanField(default=False)),
                ('remove', models.BooleanField(default=False)),
            ],
        ),
    ]
